### ISSUE TITLE
Styling Issue: Dark Mode Text Visibility

### ISSUE THREAD

**Issue by ichigo-k** [blackmann/compa#25]
I hope this message finds you well. 
I have encountered a styling issue in the application that affects text visibility in dark mode. Specifically, when dark mode is enabled, the text color remains black, making it challenging for users to read. 

![Screenshot 2024-01-29 230716](https://github.com/blackmann/compa/assets/125087781/703ea420-3735-4d11-8423-40e224828035)

**Comment by blackmann** [comment]
This seems to happen on older browsers. I’ll look into it.

thanks for reporting

**Comment by ichigo-k** [comment]
Oh okay I already forked the repo, make the necessary changes and made a pull request I hope it wouldn't be a bother
