### ISSUE TITLE
Improve error UX for conflict errors

### ISSUE THREAD

**Issue by auxibee** [blackmann/compa#32]
Resources like programs, lessons and lectures should be checked if they are already in the system and the appropriate response shown.
Application errors when a duplicate is being added. 
<img width="1440" alt="Screenshot 2024-02-03 at 9 41 46 AM" src="https://github.com/blackmann/compa/assets/21082997/af486b86-29f6-49f2-b19a-5cd18db981db">

**Comment by auxibee** [comment]
Going through the codebase i released there are no error handling
-Username/Email should be checked for uniqueness, empty fields etc when creating accounts
-Almost all the the Post actions lack error handling

Hopefully you could restructure your forms and useAsyncFetcher() to handle errors instead of The default Remix error boundary.
You can assign me to it.
Thank You.

**Comment by auxibee** [comment]
Is there a way to return errors from the server actions using your custom fetcher ? Throwing the errors gets handled by remix error boundary which is not ideal for such errors.
I am trying to return errors from the post actions but i cannot get them in the UI to show those errors.

**Comment by blackmann** [comment]
Fixed with #45
