### ISSUE TITLE
Why Request method checks ?

### ISSUE THREAD

**Issue by auxibee** [blackmann/compa#33]
Please Why are request method being checked in the actions ? 
Since actions are only called for POST requests there is no need to validate if its a post request.

**Comment by blackmann** [comment]
The `action` function is also called for `patch`, `delete`, `put`.

If you're asking in regards to using just the `post` method from the app then;

That check is only defensive. Because anyone can make a fetch request with any method to that endpoint.

**Comment by blackmann** [comment]
Also, there's a discord: https://discord.gg/5CDnysz where you can ask questions or find the related PR and make comments on it.

Issues are for bugs or feature improvements. So we don't flood this place. I'll be closing this. Let's continue in the discord if you still have questions.
