### ISSUE TITLE
RFC - Notification system

### ISSUE THREAD

**Issue by auxibee** [blackmann/compa#61]
A non-realtime notification system for Compa.

# Features
- Notify users of events such as comments added, community updates, system upgrades etc
- Implementation should allow for all generic notifications

# Implementation
Notifications are events that happen we would like to inform users about such as comment added, comment deleted, a new feature added etc.

We will have a table to capture the different kinds of events that occur in our system. For now only comment added event will be 
added

```
Event {
 id
name
}
```

A notification table which will capture the main notification  message, actor_id-optional(the user performing the event) and entity id-optional(being link to a particular post, comment etc). Some notifications will just be a message hence the actor id and entity id being optional
```
Notification {
       message
       entity_id(foreign key)
       actor_id
}
```

Notification subscribers table(many to many) will capture users and their notifications
```
{
  user_id
 notification_id
} 
```
# User story for Comment Added Event
user adds comment to a post
get all users who have comments on the post including the original poster
Notification - username has added a comment on post_title

**Comment by blackmann** [comment]
Thanks for this. Some comments:

1. `entity_id` only captures the entity's id. But we can't tell what entity that is.
2. We need to be able to know if a notification has been read by its recipient.
3. What will be the purpose of the events table?
4. We need to know when the notification was added.

**Comment by auxibee** [comment]
1. We could add entity_type to capture if its a post/comment etc.
2. Yeah a read field will be added to the notification subscribers.
3. Yeah I think it is redundant
4. Yeah sure a createdAtDate will be added.

**Comment by auxibee** [comment]
What about making it modular by separating the type of notifications ?
We have have a different table for each type of notifications like comments notifications, post notification, community notifications  etc.
In this case each notification table will store its actor id and the comment/post /etc id
We will fetch from notification subscribers and join all the notification tables.

**Comment by blackmann** [comment]
What benefits do we get from doing it like this?

**Comment by auxibee** [comment]
i was confused with how we will fetch the post/comment/etc of the notification with the initial approach and hence this new suggestion.

**Comment by blackmann** [comment]
You need to update the issue with the new fields, etc.

**Comment by auxibee** [comment]
Schema design
 ```
Notification {
id
message
actor_id
entity_id
entity_type
dateCreated
}

NotificationSuscribers{
id
notification_id
user_id
read
}
```

**Comment by blackmann** [comment]
Completed with #64
