### ISSUE TITLE
Error and Feature Enhancement

### ISSUE THREAD

**Issue by KwartengA** [blackmann/compa#73]
1. I added a course associated with its code but for that course, as there are many groups into which it is subdivided with that particular course code and course title, I am not able to add the group and so I get errors upon adding the group.

2. I cannot delete a course I mistakenly added. I want to ask if you can add a feature to permit my removing of any course I no longer want to add.

**Comment by blackmann** [comment]
1. Recommendation: Add the group in brackets to the location
2. This will be added to roadmap. Thanks for reporting.
